var OnShoreData = [{
		'sales': '311710',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 1,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 1,
		'highyielddebtriskforecast: Y': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 1,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A000159078',
		'female': 2,
		'male': 6,
		'20↓': 4,
		'20-30': 2,
		'30-40': 0,
		'40-50': 2,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 8,
		'highyielddebtriskforecast: Y': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 8,
		'area_South': 0,
		'location_台北市': 3,
		'location_新北市': 5,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 8,
		'score': 0
	},
	{
		'sales': 'A0278',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 1,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 1,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0288',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 1,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 1,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 1,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0367',
		'female': 0,
		'male': 3,
		'20↓': 0,
		'20-30': 0,
		'30-40': 2,
		'40-50': 0,
		'50-60': 0,
		'60↑': 1,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 3,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 3,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 3,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 3,
		'score': 0
	},
	{
		'sales': 'A0431',
		'female': 8,
		'male': 4,
		'20↓': 2,
		'20-30': 3,
		'30-40': 2,
		'40-50': 1,
		'50-60': 3,
		'60↑': 1,
		'highyielddebtriskforecast: N': 10,
		'highyielddebtriskforecast: Y': 2,
		'area_Center': 2,
		'area_East': 0,
		'area_North': 9,
		'area_South': 1,
		'location_台北市': 2,
		'location_新北市': 3,
		'location_基隆市': 1,
		'location_新竹市': 1,
		'location_桃園市': 1,
		'location_新竹縣': 1,
		'location_台中市': 2,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 1,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 12,
		'score': 0
	},
	{
		'sales': 'A0460',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 1,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 1,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0524',
		'female': 11,
		'male': 3,
		'20↓': 0,
		'20-30': 2,
		'30-40': 3,
		'40-50': 5,
		'50-60': 3,
		'60↑': 1,
		'highyielddebtriskforecast: N': 11,
		'highyielddebtriskforecast: Y': 3,
		'area_Center': 3,
		'area_East': 0,
		'area_North': 6,
		'area_South': 5,
		'location_台北市': 0,
		'location_新北市': 3,
		'location_基隆市': 1,
		'location_新竹市': 0,
		'location_桃園市': 1,
		'location_新竹縣': 1,
		'location_台中市': 1,
		'location_苗栗縣': 0,
		'location_彰化縣': 1,
		'location_南投縣': 0,
		'location_雲林縣': 1,
		'location_高雄市': 3,
		'location_台南市': 0,
		'location_嘉義市': 1,
		'location_嘉義縣': 0,
		'location_屏東縣': 1,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 14,
		'score': 0
	},
	{
		'sales': 'A0532',
		'female': 2,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 1,
		'40-50': 1,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 2,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 0,
		'location_台北市': 1,
		'location_新北市': 1,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'A0639',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 1,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 1,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 1,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0642',
		'female': 1,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 1,
		'50-60': 1,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 2,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 2,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 2,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'A0700',
		'female': 1,
		'male': 1,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 1,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 2,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 0,
		'location_台北市': 1,
		'location_新北市': 1,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'A0715',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 1,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 1,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0769',
		'female': 15,
		'male': 9,
		'20↓': 1,
		'20-30': 4,
		'30-40': 7,
		'40-50': 3,
		'50-60': 5,
		'60↑': 4,
		'highyielddebtriskforecast: N': 22,
		'highyielddebtriskforecast: Y': 2,
		'area_Center': 5,
		'area_East': 1,
		'area_North': 16,
		'area_South': 2,
		'location_台北市': 3,
		'location_新北市': 4,
		'location_基隆市': 1,
		'location_新竹市': 3,
		'location_桃園市': 4,
		'location_新竹縣': 1,
		'location_台中市': 3,
		'location_苗栗縣': 0,
		'location_彰化縣': 1,
		'location_南投縣': 0,
		'location_雲林縣': 1,
		'location_高雄市': 2,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 1,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 24,
		'score': 0
	},
	{
		'sales': 'A0776',
		'female': 2,
		'male': 0,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 1,
		'highyielddebtriskforecast: N': 2,
		'highyielddebtriskforecast: Y': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 2,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 2,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'A0780',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 1,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'C000467580',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 1,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 1,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'H000141315',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 1,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'J000725232',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 1,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 1,
		'highyielddebtriskforecast: Y': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 1,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'L000523853',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 1,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'LF00000001',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 1,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'N001809176',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 1,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 1,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'N001980909',
		'female': 1,
		'male': 0,
		'20↓': 1,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 1,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 1,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'R001155043',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 0,
		'highyielddebtriskforecast: Y': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 1,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 1,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'RCAM1',
		'female': 4,
		'male': 4,
		'20↓': 0,
		'20-30': 0,
		'30-40': 1,
		'40-50': 1,
		'50-60': 2,
		'60↑': 4,
		'highyielddebtriskforecast: N': 8,
		'highyielddebtriskforecast: Y': 0,
		'area_Center': 2,
		'area_East': 0,
		'area_North': 4,
		'area_South': 2,
		'location_台北市': 2,
		'location_新北市': 2,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 1,
		'location_彰化縣': 1,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 1,
		'location_台南市': 1,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 8,
		'score': 0
	},
	{
		'sales': 'S000589626',
		'female': 0,
		'male': 2,
		'20↓': 2,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'highyielddebtriskforecast: N': 2,
		'highyielddebtriskforecast: Y': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 2,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 2,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	}
]

var offShoreData = [{
		'sales': 'A000514964',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 1,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0243',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'area_Center': 1,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 1,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0257',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 1,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 1,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0264',
		'female': 1,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 1,
		'location_桃園市': 1,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'A0269',
		'female': 0,
		'male': 2,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 2,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 2,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 2,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'A0273',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 1,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 1,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'A0278',
		'female': 2,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 0,
		'location_台北市': 2,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'A0291',
		'female': 0,
		'male': 2,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 1,
		'50-60': 1,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 2,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'A110169660',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 1,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'B0059',
		'female': 1,
		'male': 2,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 2,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 1,
		'location_台北市': 2,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 1,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 3,
		'score': 0
	},
	{
		'sales': 'B0152',
		'female': 3,
		'male': 0,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 1,
		'50-60': 1,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 3,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 1,
		'location_台南市': 1,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 1,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 3,
		'score': 0
	},
	{
		'sales': 'B0165',
		'female': 5,
		'male': 3,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 4,
		'60↑': 3,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 8,
		'area_South': 0,
		'location_台北市': 2,
		'location_新北市': 5,
		'location_基隆市': 0,
		'location_新竹市': 1,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 8,
		'score': 0
	},
	{
		'sales': 'B0174',
		'female': 0,
		'male': 2,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 1,
		'50-60': 0,
		'60↑': 1,
		'area_Center': 2,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 2,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'B0211',
		'female': 6,
		'male': 3,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 2,
		'50-60': 3,
		'60↑': 4,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 8,
		'location_台北市': 1,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 6,
		'location_台南市': 1,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 1,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 9,
		'score': 0
	},
	{
		'sales': 'B0264',
		'female': 10,
		'male': 5,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 4,
		'50-60': 7,
		'60↑': 3,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 15,
		'area_South': 0,
		'location_台北市': 10,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 1,
		'location_桃園市': 4,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 15,
		'score': 0
	},
	{
		'sales': 'B120564347',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'area_Center': 1,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 1,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'B220837687',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 1,
		'50-60': 0,
		'60↑': 0,
		'area_Center': 1,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 1,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'C000082490',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 1,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'C000635482',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 1,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 1,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'C200656249',
		'female': 3,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 3,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 3,
		'area_South': 0,
		'location_台北市': 3,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 3,
		'score': 0
	},
	{
		'sales': 'C220432405',
		'female': 3,
		'male': 2,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 3,
		'60↑': 2,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 5,
		'area_South': 0,
		'location_台北市': 2,
		'location_新北市': 3,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 5,
		'score': 0
	},
	{
		'sales': 'D001396636',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 1,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 1,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'E120082665',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 0,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 0,
		'area_South': 1,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 1,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'F002177197',
		'female': 1,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 2,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 2,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'F120359206',
		'female': 1,
		'male': 0,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'area_Center': 1,
		'area_East': 0,
		'area_North': 0,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 1,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'H001713333',
		'female': 0,
		'male': 1,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 1,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 0,
		'location_基隆市': 0,
		'location_新竹市': 1,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 1,
		'score': 0
	},
	{
		'sales': 'LF00000001',
		'female': 1,
		'male': 1,
		'20↓': 0,
		'20-30': 1,
		'30-40': 0,
		'40-50': 0,
		'50-60': 1,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 0,
		'location_台北市': 0,
		'location_新北市': 1,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 1,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	},
	{
		'sales': 'R102998035',
		'female': 3,
		'male': 9,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 2,
		'50-60': 8,
		'60↑': 1,
		'area_Center': 0,
		'area_East': 2,
		'area_North': 10,
		'area_South': 0,
		'location_台北市': 8,
		'location_新北市': 1,
		'location_基隆市': 0,
		'location_新竹市': 1,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 1,
		'location_花蓮縣': 1,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 12,
		'score': 0
	},
	{
		'sales': 'RCAM2',
		'female': 0,
		'male': 2,
		'20↓': 0,
		'20-30': 0,
		'30-40': 0,
		'40-50': 2,
		'50-60': 0,
		'60↑': 0,
		'area_Center': 0,
		'area_East': 0,
		'area_North': 2,
		'area_South': 0,
		'location_台北市': 1,
		'location_新北市': 1,
		'location_基隆市': 0,
		'location_新竹市': 0,
		'location_桃園市': 0,
		'location_新竹縣': 0,
		'location_台中市': 0,
		'location_苗栗縣': 0,
		'location_彰化縣': 0,
		'location_南投縣': 0,
		'location_雲林縣': 0,
		'location_高雄市': 0,
		'location_台南市': 0,
		'location_嘉義市': 0,
		'location_嘉義縣': 0,
		'location_屏東縣': 0,
		'location_宜蘭縣': 0,
		'location_花蓮縣': 0,
		'location_台東縣': 0,
		'location_金門縣': 0,
		'location_澎湖縣': 0,
		'customer_num': 2,
		'score': 0
	}
]



$(window).scroll(function(event){
	if($(window).scrollTop()>0){
		$("nav").removeClass("navbar-top")
		$("nav").addClass("bg-light")
		$("nav").removeClass("navbar-dark")
		$("nav").addClass("navbar-light")
	}else{
		$("nav").addClass("navbar-top")
		$("nav").removeClass("bg-light")
		$("nav").removeClass("navbar-light")
		$("nav").addClass("navbar-dark")
	}
})

function get_tax_point(tax) {
	var max_tax = 135184
	var min_tax = 29157

	if (tax > max_tax) {
		return 5
	}else if (tax < min_tax) {
		return 0
	} else {
		var scale = 5 / (max_tax - min_tax)
		var convert = ((tax - min_tax) * scale)
		return Math.round(convert, 2)
	}
}

function calculate_age(born) {
	var today = new Date()
	var year = born.substring(0, 4);
	var month = born.substring(5, 7);
	var addYear = 0
	if(month-1>today.getMonth()){
		addYear = -1
	}else{
		addYear = 0
	}
	return (today.getYear() + 1900) - year + addYear

}
function get_age_point(age) {
	var max_age = 100
	var min_age = 0
	if (age > max_age) {
		return 5
	} else if (age < min_age){
		return 0
	}else {
		var scale = 5 / (max_age - min_age)
		var convert = ((age - min_age) * scale)
		return Math.round(convert, 2)
	}
}

function age_group(x) {
	if(x<=20){
		return "20↓"
	} else if (x > 20 && x <= 30){
		return "20-30"
	} else if (x > 30 && x <= 40){
		return "30-40"
	} else if (x > 40 && x <= 50){
		return "40-50"
	} else if (x > 50 && x <= 60) {
		return "50-60"
	} else if (x > 60) {
		return "60↑"
	}
}

function city_group(x) {

	var city = {
		"North": ["台北市", "新北市", "基隆市", "新竹市", "桃園市", "新竹縣"],
		"Center": ["台中市", "苗栗縣", "彰化縣", "南投縣", "雲林縣"],
		"South": ["高雄市", "台南市", "嘉義市", "嘉義縣", "屏東縣"],
		"East": ["宜蘭縣", "花蓮縣", "台東縣"],
		"Offshore_islands": ["金門縣", "澎湖縣"]
	}
	for(var area in city){
		for (let index = 0; index < city[area].length; index++) {
			if (x == city[area][index]) {
				return area
			}
		}
	}

}
function SumData(arr) {
	var sum = 0;
	for (var i = 0; i < arr.length; i++) {
		sum += arr[i];
	};
	return sum;
}

function recommend_product(user_feature) {
	var onshore = [2.075, 1, 2.2]
	var offshore = [2.745, 2.2, 3.54]

	var on_variance = []
	var off_variance = []

	for (let i = 0; i < 3; i++) {
		var on_var = (onshore[i] - user_feature[i]) ** 2
		on_variance.push(on_var)
		var off_var = (offshore[i] - user_feature[i]) ** 2
		off_variance.push(off_var)
	}

	on_similarity = SumData(on_variance)
	off_similarity2 = SumData(off_variance)

	if (on_similarity < off_similarity2){
		return "Onshore"
	}else{
		return "Offshore"
	}
}

function findProduct(birth_date, tax, seniority) {
	var age = calculate_age(birth_date)
	var age_point = get_age_point(age)
	var tax_point = get_tax_point(tax)
	seniority = seniority / 10
	return recommend_product([age_point, seniority, tax_point])
}

function get_best_sales(sales) {

	if(sales.length>0){
		var best_score = 0
		var best_sales_index = 0
		for(let i=0; i<sales.length; i++){
			if (sales[i]["score"] > best_score){
				best_score = sales[i]["score"]
				best_sales_index = i
			}
		}
		return sales[best_sales_index]["sales"]
	}else{
		return "no recommendation"
	}
}

function recommend_sales(applicant, dic) {


	//---------filter by area-----------
	var data_filter_area = []
	for (var data in dic){
		if (dic[data][applicant["area"]] > 0) {
			data_filter_area.push(dic[data])
		}
	}
	//---------filter by age-----------
	var data_filter_age = []
	for (var data in data_filter_area) {
		if (data_filter_area[data][applicant["age"]] > 0) {
			data_filter_area[data]["score"] += data_filter_area[data][applicant["age"]] / data_filter_area[data]["customer_num"]
			data_filter_age.push(data_filter_area[data])
		}
	}
	//---------filter by gender-----------
	var data_filter_gender = []
	for (var data in data_filter_age) {
		if (data_filter_age[data][applicant["gender"]] > 0) {
			data_filter_age[data]["score"] += (data_filter_age[data][applicant["gender"]] / data_filter_age[data]["customer_num"] * 0.8)
			data_filter_gender.push(data_filter_age[data])
		}
	}
	//---------filter by location-----------
	var data_filter_loc = []
	for (var data in data_filter_gender) {
		if (data_filter_gender[data][applicant["location"]] > 0) {
			data_filter_gender[data]["score"] += (data_filter_gender[data][applicant["location"]] / data_filter_gender[data]["customer_num"] * 0.6)
			data_filter_loc.push(data_filter_gender[data])
		}
	}
	if (data_filter_loc.length>0){
		return get_best_sales(data_filter_loc)
	} else if (data_filter_gender.length>0){
		return get_best_sales(data_filter_gender)
	} else if (data_filter_gender.length > 0) {
		return get_best_sales(data_filter_age)
	} else {
		return get_best_sales(data_filter_area)
	}
	
}


function findSales(birth_date, city, gender, dic) {
	var age = calculate_age(birth_date)
	var age_range = age_group(age)
	var area = "area_" + city_group(city)
	var location = "location_" + city
	var applicant = { "age": age_range, "gender": gender, "area": area, "location": location }
	return recommend_sales(applicant, dic)
}

function search() {
	var birth_date = $('#form_bir').val()
	var gender = $('#form_sex').val()
	var city = $('#form_city').val()
	var tax = $('#form_tax').val()
	var seniority = $('#form_investment').val()
	if (birth_date != "" && gender != "" && city != "" && tax != "" && seniority != ""){
		// product match
		product = findProduct(birth_date, tax, seniority)
		
		console.log(product)
		if (product =="Onshore"){
			$('#product_name').text("Onshore")
			$('.product_img').css("background-image", "url(img/Onshorefund.png)")
			// sales match
			sales = findSales(birth_date, city, gender, OnShoreData)
			console.log(sales)
			$('#sales_name').text(sales)
			$('.sales_img').css("background-image", "url(img/OnShore/" + sales +".png)")
		} else if (product == "Offshore") {
			$('#product_name').text("Offshore")
			$('.product_img').css("background-image", "url(img/Offshorefund.png)")
			// sales match
			sales = findSales(birth_date, city, gender, offShoreData)
			console.log(sales)
			$('#sales_name').text(sales)
			$('.sales_img').css("background-image", "url(img/OffShore/" + sales + ".png)")
		}
	
	}else{
		alert("請輸入完整資訊")
	}
}



var s = skrollr.init();

